[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "babylonian-image-library"
version = "1.0.1"
description = "A deterministic infinite image library generator inspired by Borges' 'The Library of Babel'. Generate unique, deterministic images based on coordinate systems without storing image data."
authors = [
    { name = "Alexander Suvorov", email = "smartlegiondev@gmail.com" }
]
license = "BSD-3-Clause"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Topic :: Multimedia :: Graphics",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "pillow>=11.1.0",
]

[project.urls]
Homepage = "https://github.com/smartlegionlab/babylonian-image-library"
Documentation = "https://github.com/smartlegionlab/babylonian-image-library"
Repository = "https://github.com/smartlegionlab/babylonian-image-library"

[tool.setuptools.packages.find]
where = ["."]